from pathlib import Path

ROOT = Path(__file__).parent.parent
DADOS_DIR = ROOT / "dados"
DADOS_BRUTOS_DIR = ROOT / "dados_brutos"
PERFIS_DIR = ROOT / "perfis"
HISTORICO_DIR = DADOS_DIR / "historico"
TORS_DIR = DADOS_BRUTOS_DIR / "tors"
TORS_TEXTO_DIR = DADOS_BRUTOS_DIR / "tors_texto"

EDITAIS_TODOS_FILE = DADOS_DIR / "editais_todos.json"
EDITAIS_PROCESSADOS_FILE = DADOS_DIR / "editais_processados.json"

OUTPUT_EXCEL = ROOT / "analise_editais_pnud.xlsx"
OUTPUT_PDF = ROOT / "relatorio_editais_pnud.pdf"

API_URL = "https://parceiros.undp.org.br/opportunities"
API_ENDPOINT = "icnim-api.undp.org.br/v1/publish/list/active"

UNESCO_API_URL = "https://apiroster.brasilia.unesco.org/api/public/published"
UNESCO_PORTAL_URL = "https://roster.brasilia.unesco.org/app/selection-process-list"

OEI_SITEMAP_INDEX = "https://oei.int/sitemap_index.xml"
OEI_PORTAL_URL = "https://oei.int/licitaciones-y-convocatorias/"

FONTES_DISPONIVEIS = ["pnud", "unesco", "oei"]

CLASSIFICACAO_TIPOS = {
    "Consultoria Pessoa Física (PF)": [
        "pessoa física",
        "consultor pessoa física",
        "consultoria individual",
        "consultor individual",
        "consultor por produto",
    ],
    "Consultoria Pessoa Jurídica (PJ) / Empresa": [
        "pessoa jurídica",
        "empresa",
        "consultoria empresarial",
    ],
    "Consultoria Especializada (não especifica PF/PJ)": [
        "consultoria especializada",
        "consultor especializado",
    ],
    "Edital Genérico / IC": [
        "ic - undp",
        "individual contractor",
        "ic -",
    ],
}

AREAS_TEMATICAS = {
    "Tecnologia da Informação / Dados": [
        "dados",
        "python",
        "gis",
        "bi",
        "sei",
        "sic",
        "automação",
        "sistema",
        "software",
        "banco de dados",
        "prototipação",
        "tecnologia",
        "digital",
        "programação",
        "geoprocessamento",
        "geoespacial",
        "levantamento de requisitos",
        "proteção de dados",
        "privacidade",
        "lgpd",
        "repositório",
    ],
    "Economia / Finanças Públicas": [
        "módulo econômico",
        "matriz de absorção",
        "absorção de investimentos",
        "calibração de parâmetros",
        "regionalização",
        "tributação",
        "tributária",
        "carga tributária",
        "economia",
        "fiscal",
        "orçamento",
        "finanças",
        "bem-estar social",
    ],
    "Saúde": ["saúde", "hospitalar", "hospital", "médico", "clínico"],
    "Estatística / Pesquisa / Metodologia": [
        "estatístico",
        "indicadores",
        "metodologia",
        "censo",
        "pesquisa",
        "dimensionamento",
        "estudo",
        "análise",
        "mapeamento",
        "sistematização",
    ],
    "Direito / Jurídico": [
        "jurídico",
        "legal",
        "penal",
        "vara",
        "cnj",
        "regulamentação",
        "normativo",
    ],
    "Meio Ambiente / Clima / Geografia": [
        "adaptação climática",
        "planos nacionais de adaptação",
        "emissões de gee",
        "gases de efeito estufa",
        "efeito estufa",
        "consumo de energia",
        "consumo de água",
        "ambiental",
        "reciclagem",
        "climático",
        "clima",
        "ecossistema",
        "costeiro",
        "geomorfológico",
        "geográfico",
        "territorial",
        "indígena",
        "comunidades tradicionais",
    ],
    "Gestão / Administração Pública": [
        "recrutamento e seleção",
        "gestão",
        "administração",
        "processos",
        "governança",
        "força de trabalho",
        "diagnóstico institucional",
        "monitoramento",
        "avaliação",
        "desenho institucional",
        "estrutura organizacional",
        "serviços compartilhados",
        "due diligence",
        "treinamento",
        "recursos humanos",
        "integridade institucional",
        "programa de integridade",
    ],
    "Educação / Ensino": [
        "educação",
        "educacao",
        "ensino",
        "educacional",
        "escolar",
        "aprendizagem",
        "pedagógico",
        "pedagogia",
        "curricular",
        "currículo",
        "bncc",
        "formação docente",
        "material didático",
        "educação popular",
    ],
    "Cultura": [
        "cultura",
        "cultural",
        "museu",
        "museologia",
        "patrimônio cultural",
        "patrimonio cultural",
        "artes",
        "artístico",
        "artistico",
        "curadoria",
        "produção cultural",
    ],
    "Comunicação": [
        "marketing promocional",
        "live marketing",
        "comunicação",
        "comunicacao",
        "comunicação institucional",
        "assessoria de imprensa",
        "imprensa",
        "jornalismo",
        "publicidade",
        "design editorial",
        "comunicação visual",
        "podcast",
    ],
    "Ciências Sociais / Participação Social": [
        "participação social",
        "participacao social",
        "participação popular",
        "participacao popular",
        "democracia participativa",
        "controle social",
        "diálogo social",
        "dialogo social",
        "ciências sociais",
        "ciencias sociais",
        "antropologia",
        "antropólogo",
        "antropologo",
        "sociologia",
        "historiador",
    ],
    "Desenvolvimento Social / Políticas Públicas": [
        "políticas públicas",
        "politicas publicas",
        "desenvolvimento social",
        "proteção social",
        "protecao social",
        "assistência social",
        "assistencia social",
        "vulnerabilidade social",
        "inclusão social",
        "inclusao social",
        "direitos sociais",
        "territórios",
        "territorios",
    ],
    "Logística / Operações": [
        "logística",
        "logistica",
        "logístico",
        "logistico",
        "logística de aplicação",
        "armazenagem",
        "transporte",
        "operações",
        "operacoes",
        "suprimentos",
        "distribuição",
        "distribuicao",
        "limpeza",
    ],
    "Planejamento / Gestão de Projetos": [
        "planejamento estratégico",
        "planejamento estrategico",
        "gestão de projetos",
        "gestao de projetos",
        "gerenciamento de projetos",
        "plano de trabalho",
        "planejamento institucional",
    ],
    "Arquitetura / Design": [
        "arquitetura",
        "arquiteto",
        "design",
        "design editorial",
        "design gráfico",
        "design grafico",
        "comunicação visual",
        "projeto gráfico",
        "projeto grafico",
        "identidade visual",
    ],
    "Trabalho / Emprego": [
        "trabalho",
        "emprego",
        "mercado de trabalho",
        "qualificação profissional",
        "qualificacao profissional",
        "formação profissional",
        "formacao profissional",
        "empregabilidade",
        "relações de trabalho",
        "relacoes de trabalho",
    ],
    "Direitos Humanos / Cidadania": [
        "direitos humanos",
        "cidadania",
        "direitos fundamentais",
        "direitos das pessoas",
        "pessoas privadas de liberdade",
        "privadas de liberdade",
        "igualdade",
        "equidade",
        "gênero",
        "genero",
        "discriminação",
        "discriminacao",
        "diversidade",
    ],
    "Segurança": [
        "segurança",
        "seguranca",
        "segurança alimentar",
        "seguranca alimentar",
        "segurança sanitária",
        "seguranca sanitaria",
        "vigilância",
        "vigilancia",
        "bombeiro",
        "segurança pública",
        "seguranca publica",
    ],
    "Ciência / Tecnologia e Inovação": [
        "inovação",
        "inovacao",
        "inovação tecnológica",
        "inovacao tecnologica",
        "núcleo de inovação tecnológica",
        "nucleo de inovacao tecnologica",
        "pesquisa e desenvolvimento",
        "ciência",
        "ciencia",
        "científico",
        "cientifico",
        "tecnologia da inovação",
    ],
    "Engenharia / Infraestrutura": [
        "serviços de engenharia",
        "engenharia civil",
        "engenharia elétrica",
        "engenharia ambiental",
        "obra",
        "obras",
        "infraestrutura",
    ],
}

DOMINIO_ORGAO = {
    "tcu.gov.br": "TCU",
    "ibge.gov.br": "IBGE",
    "gestao.gov.br": "MGI",
    "agu.gov.br": "AGU",
    "trabalho.gov.br": "MTE",
    "undp.org": "PNUD (Direto)",
}

PERFIS_DISPONIVEIS = sorted(arquivo.stem for arquivo in PERFIS_DIR.glob("*.json"))
